# MQTT Configuration
mqtt.broker=localhost
mqtt.port=1883
mqtt.topic=test/topic
mqtt.username=admin
mqtt.password=1qaz@WSX
# PostgreSQL Configuration
postgres.host=localhost
postgres.port=5432
postgres.database=mydb
postgres.username=postgres
postgres.password=123456