version: "3.8"

services:
  # ========== MQTT Broker ==========
  emqx:
    image: emqx/emqx:6
    container_name: emqx
    restart: unless-stopped
    ports:
      - "1883:1883"      # MQTT
      - "8083:8083"      # MQTT WebSocket
      - "8883:18083"    # Dashboard
    environment:
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=public
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_AUTH__USER__1__USERNAME=kircheis
      - EMQX_AUTH__USER__1__PASSWORD=panning
      - EMQX_AUTH__USER__2__USERNAME=aiofm
      - EMQX_AUTH__USER__2__PASSWORD=aiofm
      - EMQX_AUTH__USER__3__USERNAME=lyy
      - EMQX_AUTH__USER__3__PASSWORD=lyy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 400M
        reservations:
          cpus: "0.1"
          memory: 200M
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========== PostgreSQL ==========
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sensordb
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
    volumes:
      - /data/mqtt_sql/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========== Grafana ==========
  grafana:
    image: grafana/grafana:13.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=kircheis
      - GF_SECURITY_ADMIN_PASSWORD=panning
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 400M
        reservations:
          cpus: "0.1"
          memory: 200M
    volumes:
      - /data/mqtt_sql/grafana:/var/lib/grafana
    depends_on:
      postgres:
        condition: service_healthy

  # ========== MQTT -> PostgreSQL Consumer (Spring Boot) ==========
  consumer:
    image: kircheis/sensor:0.0.1
    container_name: sensor
    restart: unless-stopped
    ports:
      - "8080:8080"      # Web / Health Check
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 400M
    volumes:
      - ./application.properties:/app/application.properties
    depends_on:
      emqx:
        condition: service_healthy
      postgres:
        condition: service_healthy
